# Generated by Django 3.2.18 on 2023-12-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_likeunline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeUnline',
            new_name='LikeUnlike',
        ),
    ]
