# Generated by Django 3.2.18 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
