# Generated by Django 3.2.18 on 2024-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0002_user_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(),
        ),
    ]
