# Generated by Django 3.2.18 on 2024-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0004_remove_user_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
