# Generated by Django 3.2.18 on 2024-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20240424_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
