# Generated by Django 3.2.12 on 2024-04-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20240424_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdetail',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='workout',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='sets',
            field=models.ManyToManyField(to='training.Set'),
        ),
    ]
