# Generated by Django 3.2.12 on 2024-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20240428_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_embed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
