# Generated by Django 3.2.12 on 2024-05-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_exercise_youtube_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdetail',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
