# Generated by Django 3.2.12 on 2024-05-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20240512_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdetail',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.exercise'),
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='workoutdetail',
            name='sets',
        ),
        migrations.AddField(
            model_name='workoutdetail',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
