# Generated by Django 3.2.18 on 2023-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='itemName',
            field=models.CharField(max_length=100),
        ),
    ]
