# Generated by Django 3.2.18 on 2023-12-10 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='userWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
